version: '3.6'
services:
  jenkins:
    build: ./docker/jenkins/
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./docker/jenkins/data:/opt
      - ./docker/jenkins/home:/var/jenkins_home
    environment:
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=123456
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      - JENKINS_UC_DOWNLOAD=http://mirrors.jenkins-ci.org