version: '3'
services:
  jenkins:
    build: ./docker/jenkins/
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./docker/jenkins/data:/opt
      - ./docker/jenkins/home:/var/jenkins_home
    environment:
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=admin@1234
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      - JENKINS_UC_DOWNLOAD=http://mirrors.jenkins-ci.org
  caddy:
    image: abiosoft/caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/caddy/data/Caddyfile:/etc/Caddyfile
      - ./html:/var/www/html
    links:
      - jenkins
    restart: always